from fastapi import APIRouter, Depends, HTTPException, status, Request
from typing import Dict
from datetime import datetime
from auth.dependencies import get_current_user
from models.eula import EULAAcceptance, EULADocument

router = APIRouter(prefix="/api/eula", tags=["EULA"])

def get_db():
    """Dependency to get database instance"""
    from server import db
    return db

# Worker EULA Content
WORKER_EULA_CONTENT = """HR Bank End User License Agreement
(EULA) - Workers

Effective Date: November 15, 2024
Last Updated: November 15, 2024

**1. Introduction & Acceptance**

This End User License Agreement ("Agreement") is a binding legal contract between you ("Worker," "you," or "your") and HR Bank Inc. ("HR Bank," "we," "us," or "our"), governing your access to and use of the HR Bank platform, mobile applications, and related services (collectively, the "Platform").

By creating an account, you acknowledge that you have read, understood, and agree to be bound by this Agreement.

If you do not agree, you may not access or use the Platform.

**2. What HR Bank Does**

HR Bank is a technology platform that:
- Connects you with employment opportunities from registered Employers
- Allows you to set your work availability using calendar-type events
- Tracks your work hours via QR code and geofenced clock-in/clock-out
- Generates timesheets that are sent to Employers' payroll processors (e.g., ADP)
- Facilitates credential verification and skills matching

HR Bank is NOT:
- Your employer
- A staffing agency or employment agency
- A payroll processor
- Responsible for your wages, benefits, taxes, or workplace conditions

**3. Your Employment Relationship**

**3.1 Employment with Employers**

When you accept a job through the Platform:
- You become an employee of the Employer, not HR Bank
- The Employer is responsible for all employment obligations (wages, taxes, benefits, workplace safety, termination, etc.)
- Your employment relationship is governed by your agreement with the Employer and applicable employment laws
- HR Bank is not a party to your employment relationship

**3.2 Active Employment Period**

While you are assigned work by an Employer:
- You are considered "actively employed" by that Employer
- Your profile is not visible in the job matching engine for other Employers
- You continue to be paid through the Employer's payroll system (using their CRA payroll account number)
- You must comply with the Employer's policies, schedules, and workplace rules

**3.3 End of Work & Return to Matching**

Your employment with an Employer ends when:
- The Employer marks your assignment as "complete" or "inactive" in the Platform
- You are no longer scheduled for shifts for 14 consecutive days (automatic return to matching)
- You or the Employer terminates the employment relationship
- You request to return to the matching engine (subject to Employer approval)

Upon end of work:
- Your profile automatically returns to the job matching engine
- You become available to match with new Employers
- Your work history, ratings, and credentials remain on your profile
- You may be re-hired by the same Employer in the future

**4. Your Obligations as a Worker**

**4.1 Accurate Information**

You agree to:
- Provide accurate, current, and complete information during registration
- Ensure all certifications, skills, and credentials are valid and truthfully represented
- Update your profile promptly when information changes
- Confirm you are legally entitled to work in Canada

**4.2 Availability Management**

You agree to:
- Set and maintain accurate availability using calendar-type events (one-time or recurring)
- Update your availability promptly if your schedule changes
- Honor availability commitments when matched with Employers

**4.3 Attendance & Timekeeping**

You agree to:
- Clock in and out accurately using the Platform's QR code and geofencing features at the designated work location
- Arrive on time for scheduled shifts
- Notify your Employer immediately if you cannot attend a shift
- Review timesheets generated by the Platform for accuracy before payroll submission
- Report any timesheet errors to your Employer within 24 hours

**4.4 Professional Conduct**

You agree to:
- Maintain professionalism, punctuality, and quality of work
- Follow your Employer's workplace policies and safety rules
- Treat Employers, coworkers, and customers with respect
- Not engage in harassment, discrimination, or illegal activity

**4.5 Account Security**

You agree to:
- Keep your account credentials confidential
- Notify HR Bank immediately of any unauthorized access
- Not share your account with others
- Not allow others to clock in/out using your account

**5. Platform Features & Limitations**

**5.1 Job Matching**

- The Platform matches you with Employers based on your skills, availability, proximity, credentials, and ratings
- HR Bank does not guarantee job placements or employment
- You may accept or decline job offers at your discretion
- Employers may accept or decline your application at their discretion

**5.2 Attendance Tracking**

- You must clock in/out using QR codes and geofencing at the work location
- The Platform records your clock-in/out times and generates timesheets
- Technical issues (e.g., GPS errors, QR code failures) may occur. HR Bank is not liable for attendance tracking errors.
- You are responsible for reporting technical issues immediately

**5.3 Timesheet Generation**

- Timesheets are automatically generated based on clock-in/out data
- You must review and confirm timesheet accuracy before payroll processing
- HR Bank does not guarantee timesheet accuracy and is not liable for payroll errors or disputes

**5.4 Credential Verification**

- Your credentials (certifications, training, education) may be verified by Institutions or Employers
- Blockchain-based credentials are tamper-proof and portable
- You control who can view your credentials

**6. Platform Fees**

- HR Bank charges a $1.00 per hour worked fee, deducted from your wages by your Employer and remitted to HR Bank
- This fee is disclosed to you before accepting any job
- Fees are subject to change with 30 days' notice

**7. Data Privacy & Security**

- HR Bank collects, stores, and processes your personal data in accordance with applicable privacy laws (PIPEDA, GDPR, CCPA)
- Your data is used to facilitate job matching, attendance tracking, and credential verification
- Your data is shared with Employers only when you apply for or accept a job
- HR Bank uses bank-level encryption (AES-256) and secure protocols (HTTPS/TLS)
- See our Privacy Policy for full details

**8. Limitation of Liability**

**8.1 Platform Availability**

- HR Bank strives for 95%+ uptime but does not guarantee uninterrupted service
- HR Bank is not liable for losses due to downtime or technical issues

**8.2 Disclaimer of Warranties**

- The Platform is provided "AS IS" and "AS AVAILABLE" without warranties
- HR Bank disclaims all warranties, including merchantability and fitness for a particular purpose

**8.3 Limitation of Damages**

- HR Bank's total liability to you shall not exceed the Platform fees you paid in the 12 months preceding any claim
- HR Bank is not liable for indirect, incidental, or consequential damages

**8.4 Exclusions**

HR Bank is not liable for:
- Employment disputes, wrongful termination, or discrimination by Employers
- Wage disputes, late payments, or non-payment by Employers
- Workplace injuries or safety violations
- Payroll errors or tax withholding issues
- Timesheet inaccuracies or attendance tracking errors

All employment-related issues must be resolved directly with your Employer.

**9. Indemnification**

You agree to indemnify and hold harmless HR Bank from any claims arising from:
- Your use or misuse of the Platform
- Your violation of this Agreement or applicable laws
- Your employment relationship with Employers
- Inaccurate information you provide

**10. Termination**

**10.1 Termination by You**

You may delete your account at any time. Termination does not affect obligations incurred before termination.

**10.2 Termination by HR Bank**

HR Bank may suspend or terminate your account if:
- You violate this Agreement
- You engage in fraudulent or illegal activity
- You misrepresent your credentials or identity
- Your account poses a security risk

**10.3 Effect of Termination**

Upon termination:
- Your access to the Platform is revoked
- Your employment relationships with Employers are not affected (you remain employed until the Employer terminates you)
- HR Bank may retain your data as required by law

**11. Governing Law & Dispute Resolution**

- This Agreement is governed by the laws of Ontario and federal laws of Canada
- Disputes shall be resolved through binding arbitration in Ontario
- You waive the right to participate in class action lawsuits against HR Bank

**12. Changes to This Agreement**

HR Bank may modify this Agreement at any time. You will be notified of material changes via email or Platform notification. Continued use constitutes acceptance.

**13. Contact Information**

HR Bank Inc.
Email: support@hrbank.ca
Website: https://hrbank.ca
Address: 1597 Whitewood Drive, Belle River ON, N8L 1E6

By clicking "I Agree" or using the Platform, you acknowledge that you have read, understood, and agree to be bound by this Agreement."""

# Employer EULA Content
EMPLOYER_EULA_CONTENT = """HR Bank End User License Agreement
(EULA) - Employers

Effective Date: November 15, 2024
Last Updated: November 15, 2024

**1. Introduction & Acceptance**

This End User License Agreement ("Agreement") is a binding legal contract between
you ("Employer," "you," or "your") and HR Bank Inc. ("HR Bank," "we," "us," or "our"),
governing your access to and use of the HR Bank platform, mobile applications, and
related services (collectively, the "Platform").

By creating an account, you acknowledge that you have read, understood, and agree to
be bound by this Agreement.

If you do not agree, you may not access or use the Platform.

**2. What HR Bank Does**

HR Bank is a technology platform that:
- Connects you with verified Workers seeking employment
- Enables calendar-based shift scheduling (one-time and recurring events)
- Tracks Worker attendance via QR code and geofenced clock-in/clock-out
- Generates timesheets for integration with your payroll processor (e.g., ADP, Ceridian, Wagepoint)
- Facilitates credential verification and skills matching

HR Bank is NOT:
- An employer, staffing agency, or employment agency
- A payroll processor or financial institution
- A party to your employment relationship with Workers
- Responsible for employment law compliance, tax withholding, benefits administration, or workplace safety

**3. Your Employment Relationship with Workers**

**3.1 You Are the Employer**

When you hire a Worker through the Platform:
- The Worker becomes your employee, not an employee of HR Bank
- You are responsible for all employment obligations, including:
  - Wages, overtime, and statutory deductions (CPP, EI, income tax)
  - Workplace safety and WSIB coverage
  - Compliance with Employment Standards Act, Human Rights Code, and other applicable laws
  - Benefits, vacation pay, and termination obligations
  - Worker classification and tax reporting (T4 slips)
- Your employment relationship is governed by your agreement with the Worker, your policies, and applicable employment laws
- HR Bank is not a party to your employment relationship

**3.2 Active Employment Period**

While a Worker is assigned work by you:
- The Worker is considered "actively employed" by your company
- The Worker's profile is not visible in the job matching engine for other Employers
- You pay the Worker through your payroll system using your CRA payroll account number
- Timesheets generated by the Platform are transmitted to your payroll processor (e.g., ADP)

**3.3 End of Work & Return to Matching**

A Worker's employment with you ends when:
- You mark the Worker's assignment as "complete" or "inactive" in the Platform
- The Worker is not scheduled for shifts for 14 consecutive days (automatic return to matching)
- You or the Worker terminates the employment relationship
- The Worker requests to return to the matching engine (requires your approval)

Upon end of work:
- The Worker's profile automatically returns to the job matching engine
- The Worker becomes available to match with other Employers
- The Worker's work history, ratings, and credentials remain on their profile
- You may re-hire the Worker in the future

Important: You must ensure proper termination procedures are followed (e.g., final pay, Record of Employment, termination notice or pay in lieu) in accordance with employment laws.

**4. Your Obligations as an Employer**

**4.1 Accurate Information**

You agree to:
- Provide accurate, current, and complete business information during registration
- Provide your valid CRA payroll account number for payroll processing
- Update your profile promptly when information changes
- Ensure job postings are accurate, lawful, and non-discriminatory

**4.2 Shift Scheduling**

You agree to:
- Create accurate shift calendar events (one-time or recurring) with correct details (date, time, location, job description, pay rate)
- Provide Workers with reasonable notice of schedule changes
- Comply with scheduling requirements under applicable employment laws (e.g., three-hour rule)

**4.3 Timesheet Verification & Payroll**

You agree to:
- Review and verify timesheets generated by the Platform for accuracy before submitting to your payroll processor
- Ensure timely and accurate payment to Workers through your payroll system
- Use your CRA payroll account number for all payroll processing
- Remit statutory deductions (CPP, EI, income tax) to the CRA
- Issue T4 slips to Workers annually
- Maintain payroll records as required by law

HR Bank does not process payroll, withhold taxes, or issue T4 slips. These are your sole responsibility.

**4.4 Employment Law Compliance**

You agree to:
- Comply with all applicable employment laws, including:
  - Employment Standards Act (minimum wage, overtime, hours of work, vacation, termination)
  - Occupational Health and Safety Act (workplace safety, WSIB coverage)
  - Human Rights Code (non-discrimination, accommodation)
  - Accessibility for Ontarians with Disabilities Act (AODA)
  - Pay Equity Act, Workplace Safety and Insurance Act, etc.
- Correctly classify Workers as employees (not independent contractors)
- Provide a safe work environment and comply with WSIB requirements
- Not discriminate in hiring, scheduling, or termination

**4.5 Worker Management**

You agree to:
- Treat Workers with respect and professionalism
- Provide clear job expectations and workplace policies
- Address performance or conduct issues promptly and fairly
- Follow proper termination procedures if ending employment
- Manage the "end of work" process in the Platform (mark assignments as complete or inactive)

**4.6 Platform Fees**

You agree to:
- Pay HR Bank a $1.00 per hour worked fee for each Worker
- Deduct the Worker's portion of the Platform fee ($1.00/hour) from their wages and remit both portions to HR Bank
- Pay Platform fees within the timeframe specified by HR Bank
- Understand that fees are subject to change with 30 days' notice

**4.7 Account Security**

You agree to:
- Keep your account credentials confidential
- Notify HR Bank immediately of any unauthorized access
- Not share your account with unauthorized users
- Ensure only authorized personnel manage Worker schedules and timesheets

**5. Platform Features & Limitations**

**5.1 Job Matching**

- The Platform matches you with Workers based on skills, availability, proximity, credentials, and ratings
- HR Bank does not guarantee Worker availability or job fulfillment
- You may accept or decline Worker applications at your discretion
- Workers may accept or decline job offers at their discretion

**5.2 Attendance Tracking**

- Workers clock in/out using QR codes and geofencing at your work location
- The Platform records clock-in/out times and generates timesheets
- Technical issues (e.g., GPS errors, QR code failures) may occur. HR Bank is not liable for attendance tracking errors.
- You are responsible for verifying Worker attendance and reporting technical issues

**5.3 Timesheet Generation**

- Timesheets are automatically generated based on clock-in/out data
- You must review and verify timesheet accuracy before payroll processing
- HR Bank does not guarantee timesheet accuracy and is not liable for payroll errors, disputes, or compliance issues

**5.4 Payroll Integration**

- The Platform integrates with Third-Party Payroll Processors (e.g., ADP, Ceridian, Wagepoint) to transmit timesheet data
- You must provide your CRA payroll account number for payroll processing
- HR Bank does not process payroll, withhold taxes, or issue T4 slips
- HR Bank is not responsible for errors, delays, or failures by your payroll processor

**5.5 Credential Verification**

- Worker credentials (certifications, training, education) are verified by Institutions or Employers
- Blockchain-based credentials are tamper-proof and portable
- You can view and verify Worker credentials before hiring

**6. End of Work Management**

**6.1 Marking Assignments as Complete**

You must actively manage the "end of work" process by:
- Marking Worker assignments as "complete" or "inactive" when employment ends
- Ensuring proper termination procedures are followed (final pay, ROE, notice/pay in lieu)
- Communicating clearly with Workers about the end of employment

**6.2 Automatic Return to Matching**

If a Worker is not scheduled for shifts for 14 consecutive days, the Platform will automatically:
- Mark the Worker's assignment as "inactive"
- Return the Worker's profile to the job matching engine
- Notify both you and the Worker of the status change

You remain responsible for any outstanding payroll, termination obligations, or legal requirements.

**6.3 Re-Hiring Workers**

- Workers who have returned to the matching engine may be re-hired by you in the future
- Previous work history, ratings, and credentials remain on the Worker's profile
- Re-hiring follows the same process as initial hiring (job posting, matching, acceptance)

**7. Payment & Fees**

**7.1 Platform Fees**

- HR Bank charges a flat fee of $1.00 per hour worked per Worker
- You are responsible for deducting the Worker's portion ($1.00/hour) from their wages and remitting both portions to HR Bank
- Fees are invoiced separately or deducted automatically based on your payment arrangement

**7.2 Payment Responsibility**

- You are solely responsible for paying Workers accurately and on time through your payroll system
- HR Bank is not responsible for payment disputes, late payments, or non-payment
- Workers may file complaints or legal claims against you (not HR Bank) for wage issues

**8. Data Privacy & Security**

- HR Bank collects, stores, and processes personal data (yours and your Workers') in accordance with applicable privacy laws (PIPEDA, GDPR, CCPA)
- You are responsible for complying with privacy laws in your collection and use of Worker data
- HR Bank uses bank-level encryption (AES-256) and secure protocols (HTTPS/TLS)
- See our Privacy Policy for full details

**9. Limitation of Liability**

**9.1 Platform Availability**

- HR Bank strives for 95%+ uptime but does not guarantee uninterrupted service
- HR Bank is not liable for losses due to downtime or technical issues

**9.2 Disclaimer of Warranties**

- The Platform is provided "AS IS" and "AS AVAILABLE" without warranties
- HR Bank disclaims all warranties, including merchantability and fitness for a particular purpose

**9.3 Limitation of Damages**

- HR Bank's total liability to you shall not exceed the Platform fees you paid in the 12 months preceding any claim
- HR Bank is not liable for indirect, incidental, or consequential damages

**9.4 Exclusions**

HR Bank is not liable for:
- Employment disputes, wrongful termination, or discrimination claims
- Wage disputes, late payments, or non-payment to Workers
- Workplace injuries, safety violations, or WSIB claims
- Payroll errors, tax compliance, or T4 slip issues
- Timesheet inaccuracies or attendance tracking errors
- Third-party service failures (e.g., payroll processors, payment gateways)

All employment-related issues are your sole responsibility.

**10. Indemnification**

You agree to indemnify, defend, and hold harmless HR Bank, its officers, directors, employees, and agents from any claims, damages, losses, liabilities, and expenses (including legal fees) arising from:
- Your use or misuse of the Platform
- Your violation of this Agreement or applicable laws
- Your employment relationship with Workers
- Employment disputes, wrongful termination, or discrimination claims
- Wage disputes, workplace injuries, or safety violations
- Inaccurate information you provide on the Platform

**11. Termination**

**11.1 Termination by You**

You may terminate your account at any time by contacting HR Bank support. Termination does not relieve you of obligations incurred before termination (e.g., outstanding fees, employment obligations to Workers).

**11.2 Termination by HR Bank**

HR Bank may suspend or terminate your account immediately, without notice, if:
- You violate this Agreement
- You engage in fraudulent, illegal, or harmful activity
- You fail to pay Platform fees
- Your account poses a security or legal risk

**11.3 Effect of Termination**

Upon termination:
- Your access to the Platform is revoked
- Your employment relationships with Workers are not affected (you remain responsible for all employment obligations)
- Outstanding fees and obligations remain due
- HR Bank may retain your data as required by law or for dispute resolution

**12. Governing Law & Dispute Resolution**

- This Agreement is governed by the laws of Ontario and federal laws of Canada
- Disputes shall be resolved through binding arbitration in Ontario, except where prohibited by law
- You waive the right to participate in class action lawsuits against HR Bank

**13. Changes to This Agreement**

HR Bank may modify this Agreement at any time. You will be notified of material changes via email or Platform notification. Continued use constitutes acceptance of the revised Agreement.

**14. Miscellaneous**

**14.1 Entire Agreement**

This Agreement, together with our Privacy Policy and Terms of Service, constitutes the entire agreement between you and HR Bank.

**14.2 Severability**

If any provision is found unenforceable, the remaining provisions remain in full force.

**14.3 No Waiver**

HR Bank's failure to enforce any provision does not constitute a waiver.

**14.4 Assignment**

You may not assign this Agreement without HR Bank's prior written consent. HR Bank may assign this Agreement at any time.

**15. Contact Information**

HR Bank Inc.
Email: support@hrbank.ca
Website: https://hrbank.ca
Address: 1597 Whitewood Drive, Belle River ON, N8L 1E6

By clicking "I Agree" or using the Platform, you acknowledge that you have read, understood, and agree to be bound by this End User License Agreement."""

# Institution EULA Content
INSTITUTION_EULA_CONTENT = """HR Bank End User License Agreement
(EULA) - Institutions

Effective Date: November 15, 2024
Last Updated: November 15, 2024

**1. Introduction & Acceptance**

This End User License Agreement ("Agreement") is a binding legal contract between you ("Institution," "you," or "your") and HR Bank Inc. ("HR Bank," "we," "us," or "our"), governing your access to and use of the HR Bank platform, mobile applications, and related services (collectively, the "Platform").

By creating an account, you acknowledge that you have read, understood, and agree to be bound by this Agreement.

If you do not agree, you may not access or use the Platform.

**2. What HR Bank Does**

HR Bank is a technology platform that:
- Enables you to issue blockchain-based digital credentials to your students, graduates, and trainees
- Provides tamper-proof, portable, and verifiable credentials using Polygon blockchain and IPFS storage
- Facilitates credential verification by Employers and other third parties
- Offers demand analytics dashboards to track skill gaps and labor market trends
- Connects your graduates with employment opportunities through the job matching engine

HR Bank is NOT:
- An educational institution or training provider
- A credentialing authority or accreditation body
- A guarantor of employment outcomes for your graduates
- Responsible for the accuracy or validity of credentials you issue

**3. Your Role as an Institution**

**3.1 Credential Issuance**

As an Institution, you are authorized to:
- Issue blockchain-based digital credentials (certificates, diplomas, training completions, micro-credentials) to your students and graduates
- Define credential types, requirements, and issuance criteria
- Revoke or update credentials as needed (e.g., for fraud, policy violations, or errors)
- Bulk-issue credentials to cohorts or graduating classes

You are solely responsible for:
- Verifying that recipients have met all requirements for the credential
- Ensuring credentials are accurate, valid, and comply with your institutional policies
- Maintaining records of credential issuance and revocation
- Complying with applicable education, privacy, and accreditation laws

**3.2 Credential Verification**

You may verify credentials issued by other Institutions or Employers through the Platform. Verification is conducted via:
- QR code scanning
- Direct link access
- Search by recipient name or credential ID

HR Bank provides the technology for verification but does not guarantee the accuracy or validity of credentials issued by third parties.

**3.3 Graduate Onboarding & Job Matching**

You may invite your graduates to join the Platform and connect them with employment opportunities:
- Bulk invitations via CSV upload or individual invites
- Graduates receive personalized links to create Worker accounts
- Graduates' credentials are automatically linked to their profiles
- Graduates enter the job matching engine and are matched with Employers based on skills, availability, and credentials

You are not responsible for employment outcomes, but you may track placement rates and outcomes via the demand analytics dashboard.

**4. Your Obligations as an Institution**

**4.1 Accurate Information**

You agree to:
- Provide accurate, current, and complete institutional information during registration
- Ensure all credentials issued are accurate, valid, and comply with your institutional policies
- Update credential information promptly if errors are discovered
- Not issue fraudulent, misleading, or false credentials

**4.2 Credential Integrity**

You agree to:
- Verify that recipients have met all requirements before issuing credentials
- Maintain records of credential issuance, revocation, and updates
- Revoke credentials immediately if fraud, policy violations, or errors are discovered
- Not issue credentials for services not rendered or qualifications not earned

**4.3 Privacy & Data Protection**

You agree to:
- Comply with applicable privacy laws (PIPEDA, GDPR, CCPA, FERPA) in collecting and processing student/graduate data
- Obtain necessary consents from students/graduates before issuing credentials or sharing data
- Protect student/graduate data using appropriate security measures
- Not share student/graduate data with unauthorized third parties

**4.4 Demand Analytics Dashboard**

You may access anonymized, aggregated labor market data via the demand analytics dashboard, including:
- Skill gaps and in-demand occupations
- Employer hiring trends and credential requirements
- Geographic demand and catchment area insights
- Course recommendations based on labor market needs

You agree to:
- Use analytics data only for institutional planning, curriculum development, and student advising
- Not attempt to de-anonymize or re-identify individual Workers or Employers
- Not share analytics data with unauthorized third parties without HR Bank's consent

**4.5 Graduate Support**

You agree to:
- Provide accurate information to graduates about the Platform and job matching process
- Support graduates in creating Worker accounts and setting up profiles
- Not guarantee employment outcomes or misrepresent the Platform's capabilities
- Respect graduates' autonomy in accepting or declining job opportunities

**4.6 Account Security**

You agree to:
- Keep your account credentials confidential
- Notify HR Bank immediately of any unauthorized access
- Not share your account with unauthorized users
- Ensure only authorized personnel issue or revoke credentials

**5. Platform Features & Limitations**

**5.1 Blockchain-Based Credentials**

- Credentials are stored on the Polygon blockchain and IPFS (InterPlanetary File System)
- Credentials are tamper-proof, portable, and verifiable by third parties
- Credentials include metadata (recipient name, credential type, issuer, issue date, expiration date, etc.)
- Credentials can be revoked or updated by the issuing Institution

HR Bank does not guarantee:
- Blockchain network uptime or availability (Polygon is a third-party service)
- IPFS storage permanence (though we use Pinata for pinning)
- Credential acceptance by all Employers or third parties

**5.2 Credential Verification**

- Employers and other third parties can verify credentials via QR code, link, or search
- Verification shows credential status (active, revoked, expired) and issuer information
- HR Bank is not liable for reliance on fraudulent or inaccurate credentials issued by third parties

**5.3 Demand Analytics Dashboard**

- Provides anonymized, aggregated labor market data
- Updated regularly based on Platform activity (job postings, hires, skill requirements)
- HR Bank does not guarantee data accuracy, completeness, or timeliness
- Data is provided "as is" for informational purposes only

**5.4 Graduate Job Matching**

- Graduates are matched with Employers based on skills, availability, proximity, credentials, and ratings
- HR Bank does not guarantee job placements or employment outcomes
- Graduates and Employers make independent hiring decisions

**6. Platform Fees**

**6.1 Credential Issuance Fees**

- HR Bank charges a fee for credential issuance based on volume and service tier (pricing available upon request)
- Fees may include setup, per-credential issuance, storage, and verification costs
- Fees are subject to change with 30 days' notice

**6.2 Demand Analytics Dashboard**

- Access to the demand analytics dashboard may be included in your service tier or offered as a paid add-on
- Pricing is based on data access level and frequency

**6.3 Payment Terms**

- Fees are invoiced monthly or annually based on your service agreement
- Payment is due within 30 days of invoice date
- Late payments may result in service suspension or termination

**7. Data Privacy & Security**

- HR Bank collects, stores, and processes personal data (yours and your students'/graduates') in accordance with applicable privacy laws (PIPEDA, GDPR, CCPA, FERPA)
- You are responsible for obtaining necessary consents from students/graduates before issuing credentials or sharing data
- HR Bank uses bank-level encryption (AES-256) and secure protocols (HTTPS/TLS)
- Blockchain credentials are publicly verifiable but do not contain sensitive personal information (only metadata)
- See our Privacy Policy for full details

**8. Intellectual Property**

**8.1 Platform Ownership**

- HR Bank owns all intellectual property rights in the Platform, including software, algorithms, designs, and trademarks
- You are granted a limited, non-exclusive, non-transferable license to use the Platform for credential issuance and verification

**8.2 Credential Ownership**

- You retain ownership of the content and metadata of credentials you issue
- HR Bank retains ownership of the blockchain infrastructure and verification technology
- Graduates own their credentials and may share them with third parties at their discretion

**9. Limitation of Liability**

**9.1 Platform Availability**

- HR Bank strives for 95%+ uptime but does not guarantee uninterrupted service
- HR Bank is not liable for losses due to downtime, blockchain network failures, or IPFS storage issues

**9.2 Disclaimer of Warranties**

- The Platform is provided "AS IS" and "AS AVAILABLE" without warranties
- HR Bank disclaims all warranties, including merchantability, fitness for a particular purpose, and non-infringement

**9.3 Limitation of Damages**

- HR Bank's total liability to you shall not exceed the fees you paid in the 12 months preceding any claim
- HR Bank is not liable for indirect, incidental, or consequential damages

**9.4 Exclusions**

HR Bank is not liable for:
- Inaccurate, fraudulent, or invalid credentials issued by you or third parties
- Employment outcomes or job placement failures for your graduates
- Blockchain network failures, IPFS storage loss, or third-party service disruptions
- Data breaches or unauthorized access resulting from your failure to secure your account
- Reliance by Employers or third parties on credentials you issue

**10. Indemnification**

You agree to indemnify, defend, and hold harmless HR Bank, its officers, directors, employees, and agents from any claims, damages, losses, liabilities, and expenses (including legal fees) arising from:
- Your use or misuse of the Platform
- Your violation of this Agreement or applicable laws
- Inaccurate, fraudulent, or invalid credentials you issue
- Privacy violations or unauthorized data sharing
- Disputes with students, graduates, or third parties

**11. Termination**

**11.1 Termination by You**

You may terminate your account at any time by contacting HR Bank support. Termination does not affect:
- Credentials already issued (they remain on the blockchain)
- Outstanding fees or obligations
- Graduates' access to their credentials or the Platform

**11.2 Termination by HR Bank**

HR Bank may suspend or terminate your account immediately, without notice, if:
- You violate this Agreement
- You engage in fraudulent or illegal activity
- You fail to pay Platform fees
- Your account poses a security or legal risk

**11.3 Effect of Termination**

Upon termination:
- Your access to the Platform is revoked
- Credentials already issued remain on the blockchain and are accessible to recipients
- Outstanding fees remain due
- HR Bank may retain your data as required by law or for dispute resolution

**12. Governing Law & Dispute Resolution**

- This Agreement is governed by the laws of Ontario and federal laws of Canada
- Disputes shall be resolved through binding arbitration in Ontario, except where prohibited by law
- You waive the right to participate in class action lawsuits against HR Bank

**13. Changes to This Agreement**

HR Bank may modify this Agreement at any time. You will be notified of material changes via email or Platform notification. Continued use constitutes acceptance of the revised Agreement.

**14. Miscellaneous**

**14.1 Entire Agreement**

This Agreement, together with our Privacy Policy and Terms of Service, constitutes the entire agreement between you and HR Bank.

**14.2 Severability**

If any provision is found unenforceable, the remaining provisions remain in full force.

**14.3 No Waiver**

HR Bank's failure to enforce any provision does not constitute a waiver.

**14.4 Assignment**

You may not assign this Agreement without HR Bank's prior written consent. HR Bank may assign this Agreement at any time.

**15. Contact Information**

HR Bank Inc.
Email: support@hrbank.ca
Website: https://hrbank.ca
Address: 1597 Whitewood Drive, Belle River ON, N8L 1E6

By clicking "I Agree" or using the Platform, you acknowledge that you have read, understood, and agree to be bound by this End User License Agreement."""


@router.get("/check", response_model=Dict)
async def check_eula_acceptance(
    current_user: dict = Depends(get_current_user),
    db = Depends(get_db)
):
    """
    Check if current user has accepted the EULA
    Returns acceptance status and EULA details if not accepted
    """
    # Determine EULA type based on user type
    eula_type_map = {
        "workforce": "worker",
        "employer": "employer",
        "institution": "institution"
    }
    eula_type = eula_type_map.get(current_user["user_type"], "worker")
    
    # Check if user has accepted current version
    acceptance = await db.eula_acceptances.find_one({
        "user_id": current_user["user_id"],
        "eula_version": "1.0",
        "eula_type": eula_type,
        "accepted": True
    })
    
    if acceptance:
        return {
            "success": True,
            "data": {
                "accepted": True,
                "acceptance_date": acceptance.get("accepted_date"),
                "version": acceptance.get("eula_version")
            }
        }
    
    # User hasn't accepted - return EULA content
    eula_content_map = {
        "worker": WORKER_EULA_CONTENT,
        "employer": EMPLOYER_EULA_CONTENT,
        "institution": INSTITUTION_EULA_CONTENT
    }
    
    return {
        "success": True,
        "data": {
            "accepted": False,
            "eula_content": eula_content_map.get(eula_type, WORKER_EULA_CONTENT),
            "eula_type": eula_type,
            "version": "1.0"
        }
    }


@router.post("/accept", response_model=Dict)
async def accept_eula(
    request: Request,
    current_user: dict = Depends(get_current_user),
    db = Depends(get_db)
):
    """
    Record EULA acceptance for current user
    """
    # Determine EULA type
    eula_type_map = {
        "workforce": "worker",
        "employer": "employer",
        "institution": "institution"
    }
    eula_type = eula_type_map.get(current_user["user_type"], "worker")
    
    # Check if already accepted
    existing = await db.eula_acceptances.find_one({
        "user_id": current_user["user_id"],
        "eula_version": "1.0",
        "eula_type": eula_type
    })
    
    if existing:
        return {
            "success": True,
            "message": "EULA already accepted"
        }
    
    # Get client info
    ip_address = request.client.host if request.client else None
    user_agent = request.headers.get("user-agent", "")
    
    # Create acceptance record
    acceptance = EULAAcceptance(
        user_id=current_user["user_id"],
        user_type=current_user["user_type"],
        eula_version="1.0",
        eula_type=eula_type,
        accepted=True,
        ip_address=ip_address,
        user_agent=user_agent
    )
    
    await db.eula_acceptances.insert_one(acceptance.model_dump())
    
    return {
        "success": True,
        "data": {
            "acceptance_id": acceptance.acceptance_id,
            "accepted_date": acceptance.accepted_date.isoformat()
        },
        "message": "EULA accepted successfully"
    }


@router.get("/history", response_model=Dict)
async def get_eula_history(
    current_user: dict = Depends(get_current_user),
    db = Depends(get_db)
):
    """
    Get EULA acceptance history for current user
    """
    acceptances = await db.eula_acceptances.find({
        "user_id": current_user["user_id"]
    }, {"_id": 0}).sort("accepted_date", -1).to_list(100)
    
    # Convert datetime objects to ISO strings for JSON serialization
    for acceptance in acceptances:
        if isinstance(acceptance.get("accepted_date"), datetime):
            acceptance["accepted_date"] = acceptance["accepted_date"].isoformat()
        if isinstance(acceptance.get("created_date"), datetime):
            acceptance["created_date"] = acceptance["created_date"].isoformat()
    
    return {
        "success": True,
        "data": {
            "acceptances": acceptances,
            "total_count": len(acceptances)
        }
    }


# ==================== INSTITUTION PARTNERSHIP AGREEMENT ====================

@router.get("/partnership-agreement", response_model=Dict)
async def get_partnership_agreement(
    current_user: dict = Depends(get_current_user),
    db = Depends(get_db)
):
    """
    Get Institution Partnership Agreement (for institution users only)
    """
    if current_user["user_type"] != "institution":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Partnership Agreement is only for institution accounts"
        )
    
    from models.partnership_agreement import INSTITUTION_PARTNERSHIP_AGREEMENT, INSTITUTION_PARTNERSHIP_SHORT_SUMMARY
    
    # Check if already accepted
    acceptance = await db.partnership_agreements.find_one({
        "institution_id": current_user["user_id"],
        "agreement_version": "1.0",
        "accepted": True
    })
    
    return {
        "success": True,
        "data": {
            "accepted": bool(acceptance),
            "acceptance_date": acceptance.get("accepted_date") if acceptance else None,
            "agreement_content": INSTITUTION_PARTNERSHIP_AGREEMENT,
            "summary": INSTITUTION_PARTNERSHIP_SHORT_SUMMARY,
            "version": "1.0"
        }
    }


@router.post("/partnership-agreement/accept", response_model=Dict)
async def accept_partnership_agreement(
    request: Request,
    signatory_name: str = None,
    signatory_title: str = None,
    current_user: dict = Depends(get_current_user),
    db = Depends(get_db)
):
    """
    Accept Institution Partnership Agreement
    Requires authorized signatory information
    """
    if current_user["user_type"] != "institution":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Partnership Agreement is only for institution accounts"
        )
    
    # Get request body
    try:
        body = await request.json()
        signatory_name = body.get("signatory_name", signatory_name)
        signatory_title = body.get("signatory_title", signatory_title)
    except:
        pass
    
    if not signatory_name or not signatory_title:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Signatory name and title are required to accept the Partnership Agreement"
        )
    
    # Check if already accepted
    existing = await db.partnership_agreements.find_one({
        "institution_id": current_user["user_id"],
        "agreement_version": "1.0"
    })
    
    if existing:
        return {
            "success": True,
            "message": "Partnership Agreement already accepted",
            "data": {
                "acceptance_date": existing.get("accepted_date"),
                "signatory": existing.get("signatory_name")
            }
        }
    
    # Get institution profile
    profile = await db.institution_profiles.find_one({"institution_id": current_user["user_id"]})
    institution_name = profile.get("institution_name", "Unknown Institution") if profile else "Unknown Institution"
    
    # Create acceptance record
    now = datetime.now(timezone.utc)
    acceptance_record = {
        "agreement_id": f"PA-{uuid.uuid4().hex[:12].upper()}",
        "institution_id": current_user["user_id"],
        "institution_name": institution_name,
        "signatory_name": signatory_name,
        "signatory_title": signatory_title,
        "signatory_email": current_user.get("email"),
        "agreement_version": "1.0",
        "accepted": True,
        "accepted_date": now.isoformat(),
        "ip_address": request.client.host if request.client else None,
        "user_agent": request.headers.get("user-agent", ""),
        "created_at": now.isoformat()
    }
    
    await db.partnership_agreements.insert_one(acceptance_record)
    
    # Log the acceptance
    try:
        from services.audit_logger import audit_logger, AuditEventType
        await audit_logger.log(
            event_type=AuditEventType.DOCUMENT_UPDATED,
            actor_id=current_user["user_id"],
            action="partnership_agreement_accepted",
            resource_type="partnership_agreement",
            resource_id=acceptance_record["agreement_id"],
            description=f"Partnership Agreement accepted by {signatory_name} ({signatory_title})",
            metadata={
                "institution_name": institution_name,
                "signatory": signatory_name,
                "signatory_title": signatory_title
            }
        )
    except Exception as e:
        print(f"Failed to log partnership acceptance: {e}")
    
    return {
        "success": True,
        "data": {
            "agreement_id": acceptance_record["agreement_id"],
            "accepted_date": acceptance_record["accepted_date"],
            "signatory_name": signatory_name,
            "signatory_title": signatory_title
        },
        "message": "Partnership Agreement accepted successfully. Thank you for partnering with HR Bank!"
    }
