from fastapi import APIRouter, Depends, HTTPException, status, Request
from typing import Dict
from datetime import datetime
from auth.dependencies import get_current_user
from models.eula import EULAAcceptance, EULADocument

router = APIRouter(prefix="/api/eula", tags=["EULA"])

def get_db():
    """Dependency to get database instance"""
    from server import db
    return db

# Worker EULA Content
WORKER_EULA_CONTENT = """HR Bank End User License Agreement
(EULA) - Workers

Effective Date: November 15, 2024
Last Updated: November 15, 2024

**1. Introduction & Acceptance**

This End User License Agreement ("Agreement") is a binding legal contract between you ("Worker," "you," or "your") and HR Bank Inc. ("HR Bank," "we," "us," or "our"), governing your access to and use of the HR Bank platform, mobile applications, and related services (collectively, the "Platform").

By creating an account, you acknowledge that you have read, understood, and agree to be bound by this Agreement.

If you do not agree, you may not access or use the Platform.

**2. What HR Bank Does**

HR Bank is a technology platform that:
- Connects you with employment opportunities from registered Employers
- Allows you to set your work availability using calendar-type events
- Tracks your work hours via QR code and geofenced clock-in/clock-out
- Generates timesheets that are sent to Employers' payroll processors (e.g., ADP)
- Facilitates credential verification and skills matching

HR Bank is NOT:
- Your employer
- A staffing agency or employment agency
- A payroll processor
- Responsible for your wages, benefits, taxes, or workplace conditions

**3. Your Employment Relationship**

**3.1 Employment with Employers**

When you accept a job through the Platform:
- You become an employee of the Employer, not HR Bank
- The Employer is responsible for all employment obligations (wages, taxes, benefits, workplace safety, termination, etc.)
- Your employment relationship is governed by your agreement with the Employer and applicable employment laws
- HR Bank is not a party to your employment relationship

**3.2 Active Employment Period**

While you are assigned work by an Employer:
- You are considered "actively employed" by that Employer
- Your profile is not visible in the job matching engine for other Employers
- You continue to be paid through the Employer's payroll system (using their CRA payroll account number)
- You must comply with the Employer's policies, schedules, and workplace rules

**3.3 End of Work & Return to Matching**

Your employment with an Employer ends when:
- The Employer marks your assignment as "complete" or "inactive" in the Platform
- You are no longer scheduled for shifts for 14 consecutive days (automatic return to matching)
- You or the Employer terminates the employment relationship
- You request to return to the matching engine (subject to Employer approval)

Upon end of work:
- Your profile automatically returns to the job matching engine
- You become available to match with new Employers
- Your work history, ratings, and credentials remain on your profile
- You may be re-hired by the same Employer in the future

**4. Your Obligations as a Worker**

**4.1 Accurate Information**

You agree to:
- Provide accurate, current, and complete information during registration
- Ensure all certifications, skills, and credentials are valid and truthfully represented
- Update your profile promptly when information changes
- Confirm you are legally entitled to work in Canada

**4.2 Availability Management**

You agree to:
- Set and maintain accurate availability using calendar-type events (one-time or recurring)
- Update your availability promptly if your schedule changes
- Honor availability commitments when matched with Employers

**4.3 Attendance & Timekeeping**

You agree to:
- Clock in and out accurately using the Platform's QR code and geofencing features at the designated work location
- Arrive on time for scheduled shifts
- Notify your Employer immediately if you cannot attend a shift
- Review timesheets generated by the Platform for accuracy before payroll submission
- Report any timesheet errors to your Employer within 24 hours

**4.4 Professional Conduct**

You agree to:
- Maintain professionalism, punctuality, and quality of work
- Follow your Employer's workplace policies and safety rules
- Treat Employers, coworkers, and customers with respect
- Not engage in harassment, discrimination, or illegal activity

**4.5 Account Security**

You agree to:
- Keep your account credentials confidential
- Notify HR Bank immediately of any unauthorized access
- Not share your account with others
- Not allow others to clock in/out using your account

**5. Platform Features & Limitations**

**5.1 Job Matching**

- The Platform matches you with Employers based on your skills, availability, proximity, credentials, and ratings
- HR Bank does not guarantee job placements or employment
- You may accept or decline job offers at your discretion
- Employers may accept or decline your application at their discretion

**5.2 Attendance Tracking**

- You must clock in/out using QR codes and geofencing at the work location
- The Platform records your clock-in/out times and generates timesheets
- Technical issues (e.g., GPS errors, QR code failures) may occur. HR Bank is not liable for attendance tracking errors.
- You are responsible for reporting technical issues immediately

**5.3 Timesheet Generation**

- Timesheets are automatically generated based on clock-in/out data
- You must review and confirm timesheet accuracy before payroll processing
- HR Bank does not guarantee timesheet accuracy and is not liable for payroll errors or disputes

**5.4 Credential Verification**

- Your credentials (certifications, training, education) may be verified by Institutions or Employers
- Blockchain-based credentials are tamper-proof and portable
- You control who can view your credentials

**6. Platform Fees**

- HR Bank charges a $1.00 per hour worked fee, deducted from your wages by your Employer and remitted to HR Bank
- This fee is disclosed to you before accepting any job
- Fees are subject to change with 30 days' notice

**7. Data Privacy & Security**

- HR Bank collects, stores, and processes your personal data in accordance with applicable privacy laws (PIPEDA, GDPR, CCPA)
- Your data is used to facilitate job matching, attendance tracking, and credential verification
- Your data is shared with Employers only when you apply for or accept a job
- HR Bank uses bank-level encryption (AES-256) and secure protocols (HTTPS/TLS)
- See our Privacy Policy for full details

**8. Limitation of Liability**

**8.1 Platform Availability**

- HR Bank strives for 95%+ uptime but does not guarantee uninterrupted service
- HR Bank is not liable for losses due to downtime or technical issues

**8.2 Disclaimer of Warranties**

- The Platform is provided "AS IS" and "AS AVAILABLE" without warranties
- HR Bank disclaims all warranties, including merchantability and fitness for a particular purpose

**8.3 Limitation of Damages**

- HR Bank's total liability to you shall not exceed the Platform fees you paid in the 12 months preceding any claim
- HR Bank is not liable for indirect, incidental, or consequential damages

**8.4 Exclusions**

HR Bank is not liable for:
- Employment disputes, wrongful termination, or discrimination by Employers
- Wage disputes, late payments, or non-payment by Employers
- Workplace injuries or safety violations
- Payroll errors or tax withholding issues
- Timesheet inaccuracies or attendance tracking errors

All employment-related issues must be resolved directly with your Employer.

**9. Indemnification**

You agree to indemnify and hold harmless HR Bank from any claims arising from:
- Your use or misuse of the Platform
- Your violation of this Agreement or applicable laws
- Your employment relationship with Employers
- Inaccurate information you provide

**10. Termination**

**10.1 Termination by You**

You may delete your account at any time. Termination does not affect obligations incurred before termination.

**10.2 Termination by HR Bank**

HR Bank may suspend or terminate your account if:
- You violate this Agreement
- You engage in fraudulent or illegal activity
- You misrepresent your credentials or identity
- Your account poses a security risk

**10.3 Effect of Termination**

Upon termination:
- Your access to the Platform is revoked
- Your employment relationships with Employers are not affected (you remain employed until the Employer terminates you)
- HR Bank may retain your data as required by law

**11. Governing Law & Dispute Resolution**

- This Agreement is governed by the laws of Ontario and federal laws of Canada
- Disputes shall be resolved through binding arbitration in Ontario
- You waive the right to participate in class action lawsuits against HR Bank

**12. Changes to This Agreement**

HR Bank may modify this Agreement at any time. You will be notified of material changes via email or Platform notification. Continued use constitutes acceptance.

**13. Contact Information**

HR Bank Inc.
Email: support@hrbank.ca
Website: https://hrbank.ca
Address: 1597 Whitewood Drive, Belle River ON, N8L 1E6

By clicking "I Agree" or using the Platform, you acknowledge that you have read, understood, and agree to be bound by this Agreement."""

# Employer and Institution EULAs (simplified versions)
EMPLOYER_EULA_CONTENT = """HR Bank End User License Agreement - Employers

[Similar structure adapted for employers with focus on their responsibilities, worker management, payroll obligations, etc.]

By using HR Bank, employers agree to handle all employment obligations, payroll, taxes, and workplace safety for workers hired through the platform."""

INSTITUTION_EULA_CONTENT = """HR Bank End User License Agreement - Institutions

[Similar structure adapted for educational institutions with focus on credential issuance, verification, student data, etc.]

By using HR Bank, institutions agree to verify and issue credentials accurately and maintain student privacy."""


@router.get("/check", response_model=Dict)
async def check_eula_acceptance(
    current_user: dict = Depends(get_current_user),
    db = Depends(get_db)
):
    """
    Check if current user has accepted the EULA
    Returns acceptance status and EULA details if not accepted
    """
    # Determine EULA type based on user type
    eula_type_map = {
        "workforce": "worker",
        "employer": "employer",
        "institution": "institution"
    }
    eula_type = eula_type_map.get(current_user["user_type"], "worker")
    
    # Check if user has accepted current version
    acceptance = await db.eula_acceptances.find_one({
        "user_id": current_user["user_id"],
        "eula_version": "1.0",
        "eula_type": eula_type,
        "accepted": True
    })
    
    if acceptance:
        return {
            "success": True,
            "data": {
                "accepted": True,
                "acceptance_date": acceptance.get("accepted_date"),
                "version": acceptance.get("eula_version")
            }
        }
    
    # User hasn't accepted - return EULA content
    eula_content_map = {
        "worker": WORKER_EULA_CONTENT,
        "employer": EMPLOYER_EULA_CONTENT,
        "institution": INSTITUTION_EULA_CONTENT
    }
    
    return {
        "success": True,
        "data": {
            "accepted": False,
            "eula_content": eula_content_map.get(eula_type, WORKER_EULA_CONTENT),
            "eula_type": eula_type,
            "version": "1.0"
        }
    }


@router.post("/accept", response_model=Dict)
async def accept_eula(
    request: Request,
    current_user: dict = Depends(get_current_user),
    db = Depends(get_db)
):
    """
    Record EULA acceptance for current user
    """
    # Determine EULA type
    eula_type_map = {
        "workforce": "worker",
        "employer": "employer",
        "institution": "institution"
    }
    eula_type = eula_type_map.get(current_user["user_type"], "worker")
    
    # Check if already accepted
    existing = await db.eula_acceptances.find_one({
        "user_id": current_user["user_id"],
        "eula_version": "1.0",
        "eula_type": eula_type
    })
    
    if existing:
        return {
            "success": True,
            "message": "EULA already accepted"
        }
    
    # Get client info
    ip_address = request.client.host if request.client else None
    user_agent = request.headers.get("user-agent", "")
    
    # Create acceptance record
    acceptance = EULAAcceptance(
        user_id=current_user["user_id"],
        user_type=current_user["user_type"],
        eula_version="1.0",
        eula_type=eula_type,
        accepted=True,
        ip_address=ip_address,
        user_agent=user_agent
    )
    
    await db.eula_acceptances.insert_one(acceptance.model_dump())
    
    return {
        "success": True,
        "data": {
            "acceptance_id": acceptance.acceptance_id,
            "accepted_date": acceptance.accepted_date.isoformat()
        },
        "message": "EULA accepted successfully"
    }


@router.get("/history", response_model=Dict)
async def get_eula_history(
    current_user: dict = Depends(get_current_user),
    db = Depends(get_db)
):
    """
    Get EULA acceptance history for current user
    """
    acceptances = await db.eula_acceptances.find({
        "user_id": current_user["user_id"]
    }).sort("accepted_date", -1).to_list(100)
    
    return {
        "success": True,
        "data": {
            "acceptances": acceptances,
            "total_count": len(acceptances)
        }
    }
